### ISSUE TITLE
Fast reset key

### ISSUE THREAD

**Issue by kdx2a** [tswilliamson/nesizm#2]
Hello.
The fastest (and only) method to reset right now is to press Menu, Down, confirm, select the game, confirm.
It would be nice to have a fast reset key that could be set in the "Options > Controls" menu of the add-in, which may require double tap to avoid accidental presses.
Thank you very much for this great emulator :)

**Comment by tswilliamson** [comment]
I haven't needed reset with my play testing. Is there a particular game this is helpful for? You can always save state in the title screen ?

**Comment by kdx2a** [comment]
I tend to reset a lot on some games, it's how I like to play games.
I don't think it's "needed" but it's a nice feature I like to see in emulators.
For the "title screen savestate", sure if there is no way to do a full reset I will go for that.
Thank you for your answer 😃

**Comment by tswilliamson** [comment]
This has been added recently via the AC/On button while in-game. Enjoy!
