### ISSUE TITLE
where is the nesizm.g3a file

### ISSUE THREAD

**Issue by Nellylorey** [tswilliamson/nesizm#5]
hey yall, hackerman69420bl4ze1tman here, I have no idea where to find the nesizm.g3a file is located... I am probably saying something really dumb but I am still going to ask it.

**Comment by aviwad** [comment]
I'm guessing you're new to github! You click the Code tab, and there click the "Releases" button and you can download the v0.9 of Nesizm :)

**Comment by Nellylorey** [comment]
ok thanks :), I am indeed new to github, normally I go to the releases from homebrew stuff like this from links from other sites like reddit so thats why
