### ISSUE TITLE
will there be a "reset to default settings" feature 

### ISSUE THREAD

**Issue by Nellylorey** [tswilliamson/nesizm#6]
(yes I have no idea how to do a feature request, how could you tell) 
I was having a issue where I was testing what buttons were doing what in the settings menu and accidently remapped "up" to ... "nothing", then I realised there is no default settings button and no identifyable config file I could delete.
I know you are fixing the remap issue in another issue request... but I still want a default settings button. Will it be there?

**Comment by tswilliamson** [comment]
I have fixed the button mapping issue in release 0.95.

A reset to defaults option isn't out of the question! I can add it to my list.
